INSERT INTO tb_news (author_Name, content, date, title) VALUES ('Alex Brown', 'Viver com tecnologia é nosso modo de vida atual. Saiba que nem sempre foi assim. Até poucos anos atrás, ter um celular no bolso era status de pessoas muito ricas, ou gente que nem sabia o que fazer com o equipamento. Não estou falando de cinquenta anos atrás, mas sim de pouco mais de 15 anos. Nossa vida com tanta tecnologia como nos dias de hoje ainda é algo muito recente. Eu era um jovem adolescente quando depois de tanto encher a paciência do meu pai, ele mesmo sem ter a mínima ideia do que eu queria acabou cedendo e comprando meu primeiro computador. Era um PC XT. Seu processamento hoje cabe em uma pequena calculadora e sua memória é menor que a de um termômetro digital.', TIMESTAMP WITH TIME ZONE '2021-09-13T20:50:07.12345Z', 'VIVER COM TECNOLOGIA');
INSERT INTO tb_news (author_Name, content, date, title) VALUES ('Maria Green', 'No processo padrão de ativação do WhastApp, você recebe um SMS no celular em que usará o aplicativo. Porém, o WhatsApp também pode ser ativado em outro aparelho — inclusive um aparelho sem chip de telefonia — desde que seja digitado o código enviado ao número informado na ativação. E é exatamente esta informação que os criminosos buscarão para ativar o WhastApp para eles, fazendo com que a vítima perca o acesso ao mesmo. Após a ativação, eles ativam a verificação de duas etapas, que faz com que seja gerada uma segunda senha para o acesso a conta. Desta forma, somente eles terão acesso a conta. Mesmo que a vítima tente fazer o processo de nova autenticação no aparelho próprio, como não terá esta segunda senha, não conseguirá.', TIMESTAMP WITH TIME ZONE '2021-07-14T20:50:07.12345Z', 'PROTEJA SET WHATSAPP');

INSERT INTO news_tags (news_id, tags) VALUES (1, 'Tecnologia');
INSERT INTO news_tags (news_id, tags) VALUES (1, 'Vida');
INSERT INTO news_tags (news_id, tags) VALUES (2, 'Whatsapp');
INSERT INTO news_tags (news_id, tags) VALUES (2, 'Segurança');

INSERT INTO tb_comment (author_Name, content, date, news_id) VALUES ('Luís Henrique', 'Legal muito informativo!', TIMESTAMP WITH TIME ZONE '2021-09-14T20:50:07.12345Z', 1);
INSERT INTO tb_comment (author_Name, content, date, news_id) VALUES ('Carlos Gabriel', 'Adorei essa matéria, amo esse blog s2', TIMESTAMP WITH TIME ZONE '2021-09-14T20:50:07.12345Z', 1);
INSERT INTO tb_comment (author_Name, content, date, news_id) VALUES ('Ana Clara', 'Não consegui fazer, poderiam me ajudar?', TIMESTAMP WITH TIME ZONE '2021-09-15T20:50:07.12345Z', 2);
INSERT INTO tb_comment (author_Name, content, date, news_id) VALUES ('Vanessa Camargo', 'Muito descobrir isso, Obrigado!', TIMESTAMP WITH TIME ZONE '2021-09-15T20:50:07.12345Z', 2);
